# هذا هو ملف الإعدادات الخاص بلوحة التحكم
backend:
  name: github
  repo: your-username/your-repo-name # **مهم جداً: استبدل باسم المستخدم والمستودع الخاص بك**
  branch: main # أو master حسب اسم الفرع الرئيسي لديك

# هذا يحدد أين سيتم رفع الصور التي ترفعها من لوحة التحكم
media_folder: "images/uploads"
public_folder: "/images/uploads"

# هنا نحدد الصفحات التي يمكن تعديلها
collections:
  - name: "pages" # اسم المجموعة
    label: "الصفحات" # الاسم الذي سيظهر في لوحة التحكم
    files:
      - file: "about.html" # المسار إلى الملف الذي تريد تعديله
        label: "صفحة عن الشركة (عربي)" # اسم الصفحة في لوحة التحكم
        name: "about_ar"
        fields:
          - {label: "عنوان الصفحة في المتصفح (Title)", name: "title", widget: "string"}
          - {label: "وصف الصفحة لمحركات البحث (Description)", name: "description", widget: "text"}
          - {label: "محتوى الصفحة", name: "body", widget: "markdown"}
      - file: "about-en.html" # ملف النسخة الإنجليزية
        label: "صفحة عن الشركة (إنجليزي)"
        name: "about_en"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Page Description for SEO", name: "description", widget: "text"}
          - {label: "Page Content", name: "body", widget: "markdown"}

      # يمكنك إضافة المزيد من الصفحات هنا بنفس الطريقة
      # مثال لصفحة الخدمات
      - file: "services.html"
        label: "صفحة خدماتنا (عربي)"
        name: "services_ar"
        fields:
          - {label: "عنوان الصفحة", name: "title", widget: "string"}
          - {label: "المحتوى الرئيسي", name: "body", widget: "markdown"}
