backend:
  name: github
  repo: egy-uae/Egyptian-Emirati-Co. # لقد تحققت من هذا، وهو صحيح
  branch: main
  site_domain: egy-uae.github.io

# هذا ضروري للمصادقة
publish_mode: editorial_workflow

# هذا يحدد أين سيتم رفع الصور
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages_ar"
    label: "الصفحات (العربية)"
    files:
      - label: "صفحة عن الشركة"
        name: "about"
        file: "about.html"
        fields:
          - { label: "عنوان الصفحة (للمتصفح و SEO)", name: "title", widget: "string" }
          - { label: "وصف الصفحة (لـ SEO)", name: "description", widget: "string" }
          - { label: "العنوان الرئيسي داخل الصفحة", name: "page_title", widget: "string" }
          - { label: "محتوى الصفحة الكامل", name: "body", widget: "markdown" }
